steps:
# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/silicon-cocoa-405809/northrepo/cetibcoauto1:$SHORT_SHA'
  - '.'
# This step pushes the image to Artifact Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/silicon-cocoa-405809/northrepo/cetibcoauto1:$SHORT_SHA'
 # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  id: Run
  args: ['run', 'deploy', 'cetibcoauto1','--image', 'us-central1-docker.pkg.dev/silicon-cocoa-405809/northrepo/cetibcoauto1:$SHORT_SHA', '--region', 'us-central1', '--platform', 'gke','--cluster=autopilot-cluster-1', '--cluster-location','us-central1']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logging: CLOUD_LOGGING_ONLY